version: "3.9"

services:
  db:
    image: timescale/timescaledb-ha:pg15-latest
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trader
      POSTGRES_DB: trader_ai
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader -d trader_ai"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    command: >
      postgres -c shared_preload_libraries=timescaledb

  redis:
    image: redis:7
    ports: ["6379:6379"]

  redpanda:
    image: redpandadata/redpanda:v24.1.10
    command:
      - redpanda start --smp 1 --overprovisioned --kafka-addr 0.0.0.0:9092
        --advertise-kafka-addr redpanda:9092
    ports: ["9092:9092"]

  api:
    build: ./apps/api
    env_file: .env
    depends_on: [db, redis, redpanda]
    ports: ["8000:8000"]

  worker:
    build: ./apps/ml
    env_file: .env
    depends_on: [db, redis, redpanda]

  web:
    build: ./apps/web
    env_file: .env
    depends_on: [api]
    ports: ["3000:3000"]

volumes:
  db_data:
