services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: traderai-db
    environment:
      POSTGRES_DB: traderai
      POSTGRES_USER: traderai
      POSTGRES_PASSWORD: traderai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traderai"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: traderai-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: infra/dockerfiles/api.Dockerfile
    container_name: traderai-api
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://traderai:traderai@db:5432/traderai
      ASYNC_DATABASE_URL: postgresql+asyncpg://traderai:traderai@db:5432/traderai
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      SECRET_KEY: dev-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: infra/dockerfiles/api.Dockerfile
    container_name: traderai-worker
    command: celery -A apps.ml.worker worker --loglevel=info --concurrency=1 --max-tasks-per-child=1 -Q training
    environment:
      DATABASE_URL: postgresql://traderai:traderai@db:5432/traderai
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  worker-training2:
    build:
      context: .
      dockerfile: infra/dockerfiles/api.Dockerfile
    container_name: traderai-worker-training2
    command: celery -A apps.ml.worker worker --loglevel=info --concurrency=1 --max-tasks-per-child=1 -Q training
    environment:
      DATABASE_URL: postgresql://traderai:traderai@db:5432/traderai
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  worker-training3:
    build:
      context: .
      dockerfile: infra/dockerfiles/api.Dockerfile
    container_name: traderai-worker-training3
    command: celery -A apps.ml.worker worker --loglevel=info --concurrency=1 --max-tasks-per-child=1 -Q training
    environment:
      DATABASE_URL: postgresql://traderai:traderai@db:5432/traderai
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  worker-backfill:
    build:
      context: .
      dockerfile: infra/dockerfiles/api.Dockerfile
    container_name: traderai-worker-backfill
    command: celery -A apps.ml.worker worker --loglevel=info --concurrency=2 --max-tasks-per-child=1 -Q backfill,historical,default
    environment:
      DATABASE_URL: postgresql://traderai:traderai@db:5432/traderai
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  worker-general:
    build:
      context: .
      dockerfile: infra/dockerfiles/api.Dockerfile
    container_name: traderai-worker-general
    command: celery -A apps.ml.worker worker --loglevel=info --concurrency=2 --max-tasks-per-child=1 -Q backfill,historical,default
    environment:
      DATABASE_URL: postgresql://traderai:traderai@db:5432/traderai
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  beat:
    build:
      context: .
      dockerfile: infra/dockerfiles/api.Dockerfile
    container_name: traderai-beat
    command: celery -A apps.ml.worker beat --loglevel=info
    environment:
      DATABASE_URL: postgresql://traderai:traderai@db:5432/traderai
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: infra/dockerfiles/web.Dockerfile
    container_name: traderai-web
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
      - /app/node_modules

volumes:
  postgres_data:
