openapi: 3.0.3
info:
  title: Trader AI
  version: 0.1.0
paths:
  /backfill/start:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbols: {type: array, items: {type: string}}
                tf: {type: string}
                years: {type: integer}
      responses:
        "200": {description: started}
  /backfill/status:
    get:
      parameters:
        - in: query
          name: job_id
          schema: {type: string}
      responses:
        "200": {description: status}
  /train/run:
    post:
      responses: {"200": {description: started}}
  /train/status:
    get:
      parameters:
        - in: query
          name: job_id
          schema: {type: string}
      responses: {"200": {description: ok}}
  /backtest/run:
    post:
      responses: {"200": {description: ok}}
  /signals/generate:
    post:
      responses: {"200": {description: ok}}
