
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: timescale/timescaledb:2.14.2-pg15
        env:
          POSTGRES_USER: trader
          POSTGRES_PASSWORD: trader
          POSTGRES_DB: trader_ai
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd="pg_isready -U trader -d trader_ai" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7-alpine
        ports: [ '6379:6379' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry==1.8.3
      - name: Install deps
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Run migrations
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: trader
          DB_PASSWORD: trader
          DB_NAME: trader_ai
        run: alembic upgrade head
      - name: Tests
        run: pytest -q
