"""Add TrainingJob model

Revision ID: 93d8353d4348
Revises: 158784867c46
Create Date: 2025-10-05 07:18:28.506890

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '93d8353d4348'
down_revision: Union[str, None] = '158784867c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing timeframe enum instead of creating a new one
    timeframe_enum = sa.Enum('M1', 'M5', 'M15', 'H1', 'H4', 'D1', name='timeframe', create_type=False)

    op.create_table('training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', timeframe_enum, nullable=False),
    sa.Column('test_period_days', sa.Integer(), nullable=True),
    sa.Column('min_train_days', sa.Integer(), nullable=True),
    sa.Column('use_expanding_window', sa.Boolean(), nullable=True),
    sa.Column('current_fold', sa.Integer(), nullable=True),
    sa.Column('total_folds', sa.Integer(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('hit_rate_tp1', sa.Float(), nullable=True),
    sa.Column('avg_roc_auc', sa.Float(), nullable=True),
    sa.Column('model_id', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.model_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_jobs_id'), 'training_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_training_jobs_job_id'), 'training_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_training_jobs_model_id'), 'training_jobs', ['model_id'], unique=False)
    op.create_index(op.f('ix_training_jobs_status'), 'training_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_training_jobs_symbol'), 'training_jobs', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_jobs_symbol'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_status'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_model_id'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_job_id'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_id'), table_name='training_jobs')
    op.drop_table('training_jobs')
    # ### end Alembic commands ###
