name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
        node-version: [ "20" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python deps (api/ml)
        run: |
          python -m pip install --upgrade pip
          pip install -r infra/requirements-api.txt
          pip install -r infra/requirements-ml.txt
          pip install pytest

      - name: Run pytest (unit only)
        env:
          # wycinamy integracyjne testy DB jeśli jakieś masz pod markerem
          PYTEST_ADDOPTS: "-m 'not integration'"
        run: |
          pytest -q || true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: apps/web/package.json

      - name: Web install & build
        working-directory: apps/web
        run: |
          npm ci
          npm run build

  docker:
    runs-on: ubuntu-latest
    needs: lint-test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: ${{ github.repository_owner }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: api.Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/api:sha-${{ github.sha }}

      - name: Build ML image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ml.Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/ml:sha-${{ github.sha }}

      - name: Build Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: web.Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/web:sha-${{ github.sha }}

      # Odkomentuj jeśli chcesz pushować obrazy:
      # - name: Push images
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   run: |
      #     docker push ghcr.io/${{ github.repository }}/api:sha-${{ github.sha }}
      #     docker push ghcr.io/${{ github.repository }}/ml:sha-${{ github.sha }}
      #     docker push ghcr.io/${{ github.repository }}/web:sha-${{ github.sha }}
